POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Chatree Sridaoduan",
  "number": "66-909780043"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "66909780043"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Dr"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

###

GET http://localhost:3001/api/persons